name = "Snake"
uuid = "5efde1e9-670a-4b17-90a7-eaf10f85280a"
authors = ["JingYu Ning <foldfelis@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
Terming = "5a1048b7-9ca6-4e8a-8e2e-1f932e78ac4e"

[compat]
Terming = "0.2"
Crayons = "4.0"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
